### ISSUE TITLE
diff runner breaks if there is no file to be mutated

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [tverhoken/stryker-diff-runner#34]
When running stryker-diff-runner, and the current branch has no changed .js file, stryker-diff-runner breaks the execution instead of sending an empty list of files, leaving the stryker to decide what to do.

## To simulate:
1. Clone the '_mutation-diff_' branch of my ServeRest repository: https://github.com/PauloGoncalvesBH/ServeRest/tree/mutation-diff
2. Run 'npm install' and 'npm run test: mutation: diff'
3. At this point, the execution of stryker-diff-runner will break, as this branch has only 1 commit above the trunk branch, and no changes to the .js file.

## Evidences:

[From line 83 of the pipeline execution result](https://github.com/PauloGoncalvesBH/ServeRest/runs/1450200137?check_suite_focus=true#step:5:83)

![image](https://user-images.githubusercontent.com/29241659/100146612-f36ea500-2e78-11eb-8c3f-352f441ccfba.png)

**Comment by tverhoken** [comment]
Hello @PauloGoncalvesBH , what could be the use of running mutation tests on file diff when there is no change ?

When in this case, what could be the scenario ? Exit nicely without error and display an information message or execute full mutation tests ?

**Comment by PauloGoncalvesBH** [comment]
Hello @tverhoken, see this PR: https://github.com/tverhoken/stryker-diff-runner/pull/36
