### ISSUE TITLE
Glob patterns do not match

### ISSUE THREAD

**Issue by gennbo** [tverhoken/stryker-diff-runner#55]
Hi,

First of all, great work on the missing (and imho crucial) functionality with you package.

I've noticed, that exclusionMatchers do not exclude any of the files if they do not reference them specifically, or in other words, are written as glob patterns. Would it be possible to implement glob matching instead of inequality check? Here's the line of code I'm referring to

https://github.com/tverhoken/stryker-diff-runner/blob/e2ecb3d15cc5093c981c1d26891f53cf8f7165e1/src/index.ts#L55

I'd be happy to provide more info if needed

**Comment by tverhoken** [comment]
Hello,

Sorry for the late response. Yes it is possible. I'll look to implement it and will come back to you to check if it suits what you are looking for.

Regards.
